# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.4'

services:

  dynamo:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    hostname: dynamo
    volumes:
      - .docker/dynamo:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    depends_on:
      - dynamo
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

  # app:
  #   build:
  #     context: target
  #     dockerfile: ../Dockerfile
  #     network: host
  #   ports:
  #     - 8989:8080
  #   depends_on:
  #     - dynamo
  #     - jaeger
